return {
	WalkSpeed = 16,
	SprintSpeed = 30,

	SlideDuration = 2,
	SlideBoost = 40,
	SlideDeceleration = 60,
	MinSlideSpeed = 20,

	VaultCheckDistance = 4,
	VaultMaxHeight = 4,
	VaultHorizontalSpeedMultiplier = 1.3,
	VaultVerticalSpeedMultiplier = 1,

	VaultTopClearanceHeight = 2.5,
	VaultTopProbeInset = 0.05,

	VaultClearanceDistance = 6,
	VaultClearanceCheckLength = 2,

	VaultLandingCheckDistance = 5,
	VaultGroundCheckDistance = 5,

	VaultInitialVerticalSpeed = 12,
	VaultVerticalAcceleration = 60,
	VaultFinishVerticalSpeed = -10,

	VaultForceMultiplier = 1000,
}
