return {
	MasterVolume = 1,
	RollOffMinDistance = 5,
	RollOffMaxDistance = 50,
	Sounds = {
		Vaulting = {
			SoundIds = {
				"rbxassetid://133381787950915",
				"rbxassetid://99382296692845",
				"rbxassetid://73880574811944",
			},
			Volume = 0.6,
			Looped = false,
			PlaybackSpeedRange = NumberRange.new(0.95, 1.05),
			Cooldown = 0.25,
		},
		Sliding = {
			SoundIds = {
				"rbxassetid://138269837525273",
				"rbxassetid://134781979035978",
				"rbxassetid://9119197706",
			},
			Volume = 0.4,
			Looped = false,
			PlaybackSpeedRange = NumberRange.new(1.05, 1.1),
			Cooldown = 0.5,
		},
		LedgeGrab = {
			SoundIds = {
				"rbxassetid://136001697249474",
				"rbxassetid://91831872689971",
				"rbxassetid://87833032497218",
			},
			Volume = 0.3,
			Looped = false,
			PlaybackSpeedRange = NumberRange.new(1.5, 1.6),
			Cooldown = 0.4,
		},
		LedgeClimb = {
			SoundIds = {
				"rbxassetid://107947199422599",
			},
			Volume = 0.4,
			Looped = false,
			PlaybackSpeedRange = NumberRange.new(0.95, 1.05),
			Cooldown = 0.4,
		},
		Landing = {
			SoundIds = {
				"rbxassetid://97094575430509",
				"rbxassetid://75971619141269",
				"rbxassetid://92370465558841",
				"rbxassetid://78797946610712",
			},
			Volume = 0.7,
			Looped = false,
			PlaybackSpeedRange = NumberRange.new(0.95, 1.05),
			Cooldown = 0.2,
		},
	},
}
