return {
	MasterVolume = 1,
	RollOffMinDistance = 5,
	RollOffMaxDistance = 50,
	Sounds = {
		Vaulting = {
			SoundIds = {
				"rbxassetid://133381787950915",
				"rbxassetid://99382296692845",
				"rbxassetid://73880574811944",
			},
			Volume = 0.6,
			Looped = false,
			PlaybackSpeedRange = NumberRange.new(0.95, 1.05),
			Cooldown = 0.25,
		},
		SlidingStart = {
			SoundIds = {
				"rbxassetid://123178970726423",
			},
			Volume = 0.6,
			Looped = false,
			PlaybackSpeedRange = NumberRange.new(0.95, 1.05),
			Cooldown = 0.5,
		},
		SlidingLoop = {
			SoundIds = {
				"rbxassetid://18952286141",
			},
			Volume = 0.35,
			Looped = true,
			PlaybackSpeedRange = NumberRange.new(0.98, 1.02),
			Cooldown = 0.5,
		},
		LedgeGrab = {
			SoundIds = {
				"rbxassetid://129550476573048",
				"rbxassetid://129947985755935",
				"rbxassetid://82817615606088",
			},
			Volume = 0.7,
			Looped = false,
			PlaybackSpeedRange = NumberRange.new(0.95, 1.05),
			Cooldown = 0.4,
		},
		LedgeClimb = {
			SoundIds = {
				"rbxassetid://107947199422599",
			},
			Volume = 0.55,
			Looped = false,
			PlaybackSpeedRange = NumberRange.new(0.95, 1.05),
			Cooldown = 0.4,
		},
		Landing = {
			SoundIds = {
				"rbxassetid://97094575430509",
				"rbxassetid://75971619141269",
				"rbxassetid://92370465558841",
				"rbxassetid://78797946610712",
			},
			Volume = 0.7,
			Looped = false,
			PlaybackSpeedRange = NumberRange.new(0.95, 1.05),
			Cooldown = 0.2,
		},
	},
}
